#ifndef HID_IDS_H_FILE
#define HID_IDS_H_FILE

#define HID_UP_LNVENDOR		0xffa00000

#define USB_VENDOR_ID_LENOVO		0x17ef
#define USB_DEVICE_ID_LENOVO_TPKBD	0x6009
#define USB_DEVICE_ID_LENOVO_CUSBKBD	0x6047
#define USB_DEVICE_ID_LENOVO_CBTKBD	0x6048

#endif
